### ISSUE TITLE
-dev flag

### ISSUE THREAD

**Issue by rkjdid** [solar3s/goregen#14]
should be taken into consideration in connection watcher loop, or it will try all available COM ports on any connection loss

https://github.com/solar3s/goregen/blob/master/main.go#L55-L63
https://github.com/solar3s/goregen/blob/master/regenbox/watcher.go#L17-L19
https://github.com/solar3s/goregen/blob/master/regenbox/watcher.go#L73

**Comment by kepon85** [comment]
Je suppose que ça correspond à ça cet issu :
Quand je spécifie un device (via -dev /dev/ttyUSB1 par exemple) ça fonctionne puis dès qu'il y a un timeout il tente de se connecter mais ne considère plus l'argument, j'ai l'impression qu'il se connecte à /dev/ttyS0
Le problème c'est que j'ai plusieurs périphérique de ce type sur cet ordinateur

Constaté sous Linux ARM

**Comment by rkjdid** [comment]
yep, je t'ai vu en parler sur slack je crois

**Comment by kepon85** [comment]
C'est ça !
