### ISSUE TITLE
mkdir no such file or directory

### ISSUE THREAD

**Issue by Hiyoshinobu** [solar3s/goregen#9]
Hello world,
I've got an issue about launching goregen.
I've just made the update (with $ go get -u -v github.com/solar3s/goregen)
ordin@ordin:~$ goregen
2017/07/26 12:34:16 couldn't mkdir "": mkdir : no such file or directory

Thanks to you!

**Comment by rkjdid** [comment]
this is due to an unspecified (or empty string) entry for a required folder in the config. You need to delete your (outdated or erronous) config file or use an up-to-date version. The error message isn't very clear sorry about that.

**Comment by rkjdid** [comment]
info about what config value failed should be prepended to these potential fails. look for `log.Fatal` entries, should be only in `main.go`
